-- +migrate Up
CREATE TABLE IF NOT EXISTS tracked_addresses (
    id SERIAL PRIMARY KEY,
    address VARCHAR(34) NOT NULL UNIQUE,
    balance DECIMAL(20,8) NOT NULL DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS tracked_addresses; 